### ISSUE TITLE
Poetry doesn't install all packages

### ISSUE THREAD

**Issue by frycupl** [ContentAutomation/TwitchCompilationCreator#17]
`poetry install                                
Installing dependencies from lock file

Package operations: 5 installs, 0 updates, 0 removals

  • Installing h5py (2.10.0): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/67/73/11/59cd898ab55f65d9213500215b00e663dafb02beb2e48301f1ffc078ae/h5py-2.10.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/67/73/11/59cd898ab55f65d9213500215b00e663dafb02beb2e48301f1ffc078ae/h5py-2.10.0.tar.gz
  Building wheels for collected packages: h5py
    Building wheel for h5py (setup.py): started
    Building wheel for h5py (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2u4zdnys
         cwd: /tmp/pip-req-build-1j4ru1qt/
    Complete output (64 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/h5py
    copying h5py/h5py_warnings.py -> build/lib.linux-x86_64-3.9/h5py
    copying h5py/__init__.py -> build/lib.linux-x86_64-3.9/h5py
    copying h5py/highlevel.py -> build/lib.linux-x86_64-3.9/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.9/h5py
    copying h5py/version.py -> build/lib.linux-x86_64-3.9/h5py
    creating build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/compat.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/vds.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.9/h5py/_hl
    creating build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_base.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5p.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_filters.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_slicing.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_datatype.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_attrs.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_attrs_data.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5pl.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5t.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_objects.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_file2.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_file_image.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_deprecation.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_attribute_create.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_file.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_group.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_selections.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_completions.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_h5f.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_threads.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dtype.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dataset.py -> build/lib.linux-x86_64-3.9/h5py/tests
    copying h5py/tests/test_dimension_scales.py -> build/lib.linux-x86_64-3.9/h5py/tests
    creating build/lib.linux-x86_64-3.9/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
    copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
    running build_ext
    Loading library to get version: libhdf5.so
    error: libhdf5.so: cannot open shared object file: No such file or directory
    ----------------------------------------
    ERROR: Failed building wheel for h5py
    Running setup.py clean for h5py
  Failed to build h5py
  Installing collected packages: h5py
      Running setup.py install for h5py: started
      Running setup.py install for h5py: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x7f_xgav/install-record.txt --single-version-externally-managed --compile --install-headers /root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/include/site/python3.9/h5py
           cwd: /tmp/pip-req-build-1j4ru1qt/
      Complete output (64 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-x86_64-3.9/h5py
      copying h5py/__init__.py -> build/lib.linux-x86_64-3.9/h5py
      copying h5py/highlevel.py -> build/lib.linux-x86_64-3.9/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.9/h5py
      copying h5py/version.py -> build/lib.linux-x86_64-3.9/h5py
      creating build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.9/h5py/_hl
      creating build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/common.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_deprecation.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_threads.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.linux-x86_64-3.9/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.linux-x86_64-3.9/h5py/tests
      creating build/lib.linux-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-3.9/h5py/tests/test_vds
      running build_ext
      Loading library to get version: libhdf5.so
      error: libhdf5.so: cannot open shared object file: No such file or directory
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1j4ru1qt/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x7f_xgav/install-record.txt --single-version-externally-managed --compile --install-headers /root/.cache/pypoetry/virtualenvs/twitchcompilationcreator-1vuCogfD-py3.9/include/site/python3.9/h5py Check the logs for full command output.
  

  at ~/.poetry/lib/poetry/utils/env.py:1101 in _run
      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│ 
      1103│         return decode(output)
      1104│ 
      1105│     def execute(self, bin, *args, **kwargs):`

I've followed the guide and got this error appear after trying to poetry install
looks like it doesn't install h5py,jinja2,moviepy,streamlink,tensorflow 
(reinstal doesn't work)

**Comment by lucaSchilling** [comment]
This looks like a problem on the side of h5py. Your venv path looks like you are using python3.9 we only used it with 3.8 so this may be the problem. I found this issue on h5py's github which mentions problems with python 3.9 maybe you can try if that fix helps u.

https://github.com/h5py/h5py/issues/1692

other then that try to downgrade and use python 3.8 as we did or give me some more context what OS are you using? What python and poetry version?
