### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'vod_offset'

### ISSUE THREAD

**Issue by OPgamemasterYt** [ContentAutomation/TwitchCompilationCreator#22]
Here is the code
warning:root:No model for prediction available -> every clip is chosen as valid (ingame)
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    ch.get_clips(
  File "C:\Users\Amogh\Desktop\TwitchCompilationCreator-2.0\src\ClipHandler.py", line 46, in get_clips
    self.get_game_clips(utils.get_headers(), timespan, language, kwargs)
  File "C:\Users\Amogh\Desktop\TwitchCompilationCreator-2.0\src\ClipHandler.py", line 78, in get_game_clips
    self.handle_response_data(resp.json(), language, creator_counts, filter_information)
  File "C:\Users\Amogh\Desktop\TwitchCompilationCreator-2.0\src\ClipHandler.py", line 136, in handle_response_data
    current_clip = Clip(**clip)
TypeError: __init__() got an unexpected keyword argument 'vod_offset'
then it stops working

**Comment by lucaSchilling** [comment]
Hey, have you installed everything via porety Install? It looks like a dependency has a newer versuon that it should have.

**Comment by OPgamemasterYt** [comment]
Yes i have installed everything via poetry install but it also asked me to update afterwards and so I did. Is there any way to revert this however?

**Comment by lucaSchilling** [comment]
Yeah ja restore the original pyproject.toml and poetry lock abd then run portey install again.

**Comment by OPgamemasterYt** [comment]
how do i restore the original pyproject.toml and poetry lock

**Comment by lucaSchilling** [comment]
If you are using git discard your changes you can google how to do that. Otherwise just download those two files and replace them in the project folder or edit those two files and copy paste the content from our repository into them.

**Comment by OPgamemasterYt** [comment]
i replaced the files and it still has the same error

**Comment by lucaSchilling** [comment]
Have you eun poetry install after replacing them? What program do you mean by 2.0?

**Comment by OPgamemasterYt** [comment]
The 2.0 version of this repository and I have run poetry install after replacing them

**Comment by lucaSchilling** [comment]
Can you run poetry show and post a screenshot of what dependencies are installed in your environment?

**Comment by MorMundHS-MA** [comment]
@OPgamemasterYt Twitch updated their API including a new property in their response. We fixed this issue so after a pull it should now work as expected. Thank you for reporting this issue!

**Comment by OPgamemasterYt** [comment]
how do i fix it?

**Comment by MorMundHS-MA** [comment]
Run `git pull` in the project's directory and then re-run it using `poetry run python main.py`. The error should be gone.

**Comment by OPgamemasterYt** [comment]
says fatal: not a git repository

**Comment by MorMundHS-MA** [comment]
Ah yes you downloaded the `.zip` I assume? You can either download the [updated `.zip`](https://github.com/ContentAutomation/TwitchCompilationCreator/archive/refs/heads/main.zip) or clone the repository with `git clone https://github.com/ContentAutomation/TwitchCompilationCreator.git` although you might have to clone it to an empty directory.

**Comment by OPgamemasterYt** [comment]
I have gotten this new error
OSError: MoviePy Error: creation of None failed because of the following error:

[WinError 2] The system cannot find the file specified.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by MorMundHS-MA** [comment]
Well, since you are on Windows I'd take care reading through the ImageMagick installation instructions and the error message itself
```
This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

Note that your `config.py` file may have been overridden by the new version, so make sure everything is correct there.

**Comment by OPgamemasterYt** [comment]
I've changed the bottom of my config_defaults.py to 
FFMPEG_BINARY = 'ffmpeg-imageio'
#~ IMAGEMAGICK_BINARY = 'auto-detect'
IMAGEMAGICK_BINARY = "C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\magick.exe"
and it is still not working
